In [1]:
import torch

In [2]:
def exp_reducer(x):
    return x.exp().sum(dim=1)

x = torch.rand(2,2)
x 

tensor([[0.1366, 0.6520],
        [0.1975, 0.7583]])

In [3]:
y = exp_reducer(x)
y 

tensor([3.0659, 3.3529])

In [4]:
J = torch.autograd.functional.jacobian(exp_reducer, x)
J.shape 

torch.Size([2, 2, 2])

In [5]:
J 

tensor([[[1.1464, 1.9194],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [1.2183, 2.1346]]])

In [6]:
def exp_adder(x, y):
    return 2 * x.exp() + 3 * y

inputs = (torch.rand(2), torch.rand(2))
inputs 

(tensor([0.2439, 0.5323]), tensor([0.4516, 0.0659]))

In [8]:
output = exp_adder(inputs[0], inputs[1])
output 

tensor([3.9072, 3.6033])

In [11]:
J = torch.autograd.functional.jacobian(exp_adder, inputs)
len(J)

2

In [12]:
J[0]

tensor([[2.5525, 0.0000],
        [0.0000, 3.4056]])

In [13]:
J[1]

tensor([[3., 0.],
        [0., 3.]])

In [17]:
print(2*inputs[0][1].exp())

tensor(3.4056)


In [18]:
x_grad = torch.matmul(torch.transpose(J[0], 0, 1), torch.ones_like(output))
x_grad 

tensor([2.5525, 3.4056])

In [19]:
y_grad = torch.matmul(torch.transpose(J[1], 0, 1), torch.ones_like(output))
y_grad  

tensor([3., 3.])